#+title: Computing $\ell_1$ distance to origin on a Spiral over the Natural Numbers
#+latex_header: \usepackage{mathtools}
#+latex_header: \DeclarePairedDelimiter{\ceil}{\lceil}{\rceil}
#+author: Andrew Shaw <shawa1@tcd.ie>
* Abstract
We present a coordinate space for addressing elements on the Integer Spiral
which is rotationally symmertric 90\deg about the origin (1). We develop and
present useful supporting formulae, in terms of some integer $n$, for computing
the coordinates of $n$ in this space, with a view to computing the $\ell_1$
(taxicab) distance from $n$ to the origin.

* Introduction
We define a Spiral over some ordered set $S$ to be an arrangement of the
elements of $S$ in an $N \times N$ grid - where $N$ is odd - such that the least
element of $S$ is in the centre, with the elements arranged in a
counter-clockwise fashion, spiralling outward from the centre.

An example of one such Spiral is the Spiral over the Natural numbers, which we
will denote as $\mathcal{N}$:

#+BEGIN_SRC 
DIAGRAM OF THE SPIRAL
#+END_SRC

As with any ordered set, it will prove useful to develop a distance metric for
different elements of $\mathcal{N}$, not least for solving part one of day three
of the 2017 edition of the /Advent of Code/. Per the problem, we will concern
ourselves with the $\ell_1$ of some element $n \in \mathcal{N}$ to the origin, 1.


** Shells in the Spiral
When dealing with elements in $\mathcal{N}$, it will prove useful to partition
$\mathcal{N}$ into subsets radiating outward from the origin, which we will call
/shells/, denoted as $S_n$, where $n$ is the number of shells between $S_n$ and
the origin. See, for example, $S_0$, $S_1$, and $S_5$, below, highlighted each
in red, white and green, respectively:

#+BEGIN_SRC 
Highlighted DIAGRAM OF THE SPIRAL
#+END_SRC

** Boundary numbers
We define the /boundary number/ of a shell to be the greatest number in that
shell, so-called as it marks the boundary between two successive shells when
following the spiral from the center.

We can see by inspection that boundary numbers of $S_0$, $S_1$, and $S_3$ are 0,
9, 25, and 49. Noting that this is simply the sequence of squares of odd
numbers, in general, the boundary number for $S_n$ is
simply

$$ b(n) = (2n + 1)^2 $$

The inverse [fn:1] of this function 

$$ b^{-1}(S) = \frac{1}{2} (\sqrt{x} - 1) $$

will, given a boundary number, yield its shell number.


Further treatment of this function is required should we wish to find the shell
number of /any/ number, not just a boundary number.

A commonly known method of finding the /next closest/ square of some real number
$x$ is to compute $\ceil*{\sqrt{x}} ^ 2$. A back of napkin proof of this would
look something like: A square number is one whose square root is an integer. The
ceiling of $x$ is the next nearest integer to $x$. Thus the ceiling of
the square root of $x$ is the next nearest integer to its square root, i.e. the
next nearest square root of a square number. Thus, the square of this will be
the next nearest square to $x$.


We will use a similar technique to find the next nearest boundary number.
Noting that the boundary numbers are in fact the squares of odd numbers,
generated by $(2x+n)^2$, and following the same logic as the previous proof, it
stands to -weasel- reason that, as the next nearest square to $x$ is the square
of the ceiling of the root of x, the next nearest odd square will be

$$ ceil(b(x))


* Footnotes

[fn:1] $b$ is invertible as of course we are ignoring the
case where $n$ is negative, as the notion of ``shell -1'' is clearly absurd
